USE SEARCHSERVICE_DB;

DROP TABLE IF EXISTS MOVIE_GENRE;
DROP TABLE IF EXISTS MOVIE_DIRECTOR;
DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS DIRECTOR;

DROP DATABASE IF EXISTS SEARCHSERVICE_DB;