USE RENTVIEWFRONTENDSERVICE;

DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS RENTAL;
DROP TABLE IF EXISTS MOVIE_GENRE;
DROP TABLE IF EXISTS MOVIE_DIRECTOR;
DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS DIRECTOR;
DROP TABLE IF EXISTS MEMBER;

-- IF NEEDED:
-- DROP DATABASE IF EXISTS RENTVIEWFRONTENDSERVICE;